# Enable Gradle Configuration Cache -> https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache=true
# Enable Gradle Build Cache -> https://docs.gradle.org/current/userguide/build_cache.html
org.gradle.caching=true
# For cloudflare certificates
org.gradle.jvmargs=-Djavax.net.ssl.trustStore=cloudflare-truststore.jks -Djavax.net.ssl.trustStorePassword=changeit